codecov:
  branch: main

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        require_changes: false
    patch:
      default:
        target: auto
        threshold: 0%
        informational: true     # patch는 정보용으로만
