# codecov.yml
codecov:
  require_ci_to_pass: no

comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: false

coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: 80%
