comment:
  layout: 'header, diff, flags, files, footer'
  behavior: default
  require_changes: false

coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: 80%
