import './globals.css';

import type { Metadata } from 'next';

import { initServerMSW } from '@/lib/msw';

import { pretendard } from '../lib/fonts';
import { Providers } from './Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

await initServerMSW();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${pretendard.className} ${pretendard.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
